#!/bin/bash

echo "🔧 Gradle Wrapper 복구 스크립트"
echo "=============================="

PROJECT_ROOT=$(pwd)

# Gradle wrapper 파일 내용
create_gradle_wrapper() {
    local SERVICE_DIR=$1
    
    # gradle/wrapper 디렉토리 생성
    mkdir -p "$SERVICE_DIR/gradle/wrapper"
    
    # gradle-wrapper.properties 생성
    cat > "$SERVICE_DIR/gradle/wrapper/gradle-wrapper.properties" << 'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.13-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF
    
    # gradlew 스크립트 생성
    cat > "$SERVICE_DIR/gradlew" << 'EOF'
#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Follow symlinks
while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        app_path=$link
    else
        app_path=$(dirname "$app_path")/$link
    fi
done

# Get standard environment variables
APP_NAME=$(basename "$0")
APP_BASE_NAME=$(basename "$0" .sh)
APP_HOME=$(cd "$(dirname "$0")" && pwd)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

# OS specific support
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
    CYGWIN*) cygwin=true;;
    Darwin*) darwin=true;;
    MINGW*) msys=true;;
    NONSTOP*) nonstop=true;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi

# Increase the maximum file descriptors if we can.
if [ "$darwin" = false ] && [ "$nonstop" = false ]; then
    case $MAX_FD in
        max*)
            MAX_FD=$(ulimit -H -n) || true
        ;;
    esac
fi

# Collect JVM options
JVM_OPTS=

# Execute Gradle
exec "$JAVACMD" $JVM_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
EOF
    
    # 실행 권한 부여
    chmod +x "$SERVICE_DIR/gradlew"
    
    echo "✅ $SERVICE_DIR: Gradle Wrapper 생성 완료"
}

# 각 서비스에 대해 Gradle Wrapper 생성
for service in eureka-discovery-service gateway-service auth-service user-service backend; do
    SERVICE_DIR="$PROJECT_ROOT/apps/$service"
    if [ -d "$SERVICE_DIR" ]; then
        echo "처리 중: $service"
        create_gradle_wrapper "$SERVICE_DIR"
        
        # gradle-wrapper.jar 다운로드
        cd "$SERVICE_DIR"
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "gradle-wrapper.jar 다운로드 중..."
            curl -L https://github.com/gradle/gradle/raw/v8.13.0/gradle/wrapper/gradle-wrapper.jar \
                 -o gradle/wrapper/gradle-wrapper.jar
        fi
        cd "$PROJECT_ROOT"
    fi
done

echo ""
echo "✅ 모든 서비스의 Gradle Wrapper가 복구되었습니다!"
echo ""
echo "이제 다음 명령어로 서비스를 실행할 수 있습니다:"
echo "  ./start-all-services.sh"
