name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build Backend Services
      run: |
        cd apps/eureka-discovery-service && ./gradlew build
        cd ../gateway-service && ./gradlew build
        cd ../auth-service && ./gradlew build
        cd ../user-service && ./gradlew build
        cd ../backend && ./gradlew build
    
    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.services.yml build
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker Images
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.services.yml push
    
    # AWS EC2 배포시
    - name: Deploy to EC2
      if: ${{ secrets.EC2_HOST }}
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/team11-project
          git pull
          docker-compose down
          docker-compose pull
          docker-compose up -d
